apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    [mysqld]
    log-bin=mysqllog # 此参数表示启用binlog功能，并指定路径名称
    skip-name-resolve # 不再进行反解析（ip不反解成域名），这样可以加快数据库的反应时间
  slave.cnf: |
    [mysqld]
    super-read-only
    skip-name-resolve
    log-bin=mysqllog
    replicate-ignore-db=mysql
