apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  clusterIP: None # headless service, 用于在Etcd中保存一个DNS记录, 可以通过<pod-name>.<svc-name>.<namespace>.svc.cluster.local来获取IP, 用于管理写操作
  ports:
  - name: mysql
    port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql
  labels:
    app: mysql
spec: # 默认不设置, 应该是一个ClusterIP类型的service, 不需要用DNS去解析获得Pod, 读请求可以转发到任何的Pod上
  selector:
    app: mysql
  ports:
  - name: myjob
    port: 3306

